SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO

CREATE OR ALTER PROCEDURE dbo.spGetUserRole
    @UserId UNIQUEIDENTIFIER
AS
BEGIN
   SET NOCOUNT ON

   SELECT r.RoleId, RoleName FROM [User] u
   LEFT JOIN [Role] r ON r.RoleId = u.RoleId
   WHERE UserId = @UserId;
END
GO
