SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO

CREATE OR ALTER PROCEDURE dbo.spCheckUserName
   @UserName VARCHAR(100)
AS
BEGIN
   SET NOCOUNT ON

   SELECT COUNT(*) FROM [User] 
   WHERE UserName = @UserName;
END
GO
