USE AlgoHub
GO

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO

CREATE OR ALTER PROCEDURE dbo.spGetUserById
    @UserId UNIQUEIDENTIFIER
AS
BEGIN
   SET NOCOUNT ON

   SELECT UserId, UserName, FullName, Email, IconName FROM [User] WHERE UserId = @UserId;
END
GO

/** ROLLBACK **
DROP PROCEDURE dbo.spGetUserById
*/
