SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO

CREATE OR ALTER PROCEDURE dbo.spGetProblemVote
   @ProblemId INT,
   @AuthorId UNIQUEIDENTIFIER
AS
BEGIN
   SET NOCOUNT ON

   SELECT IsUpvote FROM ProblemVote
   WHERE ProblemId = @ProblemId AND AuthorId = @AuthorId;
END
GO
