USE AlgoHub
GO

SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET QUOTED_IDENTIFIER ON
GO

IF EXISTS(SELECT * FROM sys.views WHERE name = 'UserRole' AND SCHEMA_NAME(schema_id) = 'dbo')
   DROP VIEW dbo.UserRole
GO

IF EXISTS(SELECT * FROM sys.tables WHERE name = 'tblUserRole' AND SCHEMA_NAME(schema_id) = 'dbo')
   DROP TABLE dbo.tblUserRole
GO

CREATE TABLE dbo.tblUserRole
(
   UserRoleId INT NOT NULL IDENTITY(1,1)
      CONSTRAINT PK_UserRole PRIMARY KEY CLUSTERED,
   UserId UNIQUEIDENTIFIER
      CONSTRAINT FK_UserRole_User FOREIGN KEY REFERENCES tblUser(UserId) ON DELETE CASCADE,
   RoleId INT
      CONSTRAINT FK_UserRole_Role FOREIGN KEY REFERENCES tblRole(RoleId) ON DELETE CASCADE,
   CreateDate DATETIME2(2) NOT NULL
      CONSTRAINT DFT_UserRole_CreateDate DEFAULT SYSUTCDATETIME(),
   UpdateDate DATETIME2(2) NOT NULL
      CONSTRAINT DFT_UserRole_UpdateDate DEFAULT SYSUTCDATETIME()
)
GO

CREATE VIEW dbo.UserRole AS SELECT * FROM dbo.tblUserRole
GO
