SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET QUOTED_IDENTIFIER ON
GO

IF EXISTS(SELECT * FROM sys.views WHERE name = 'Tag' AND SCHEMA_NAME(schema_id) = 'dbo')
   DROP VIEW dbo.Tag
GO

IF EXISTS(SELECT * FROM sys.tables WHERE name = 'tblTag' AND SCHEMA_NAME(schema_id) = 'dbo')
   DROP TABLE dbo.tblTag
GO

CREATE TABLE dbo.tblTag
(
   TagId INT NOT NULL IDENTITY(1, 1)
      CONSTRAINT PK_Tag PRIMARY KEY CLUSTERED,
   TagName NVARCHAR(50) NOT NULL
      CONSTRAINT UNQ_Tag_TagName UNIQUE,
   CreateDate DATETIME2(2) NOT NULL
      CONSTRAINT DFT_Tag_CreateDate DEFAULT SYSUTCDATETIME(),
   UpdateDate DATETIME2(2) NOT NULL
      CONSTRAINT DFT_Tag_UpdateDate DEFAULT SYSUTCDATETIME()
)
GO

CREATE VIEW dbo.Tag AS SELECT * FROM dbo.tblTag
GO
