SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET QUOTED_IDENTIFIER ON
GO

IF EXISTS(SELECT * FROM sys.views WHERE name = 'Test' AND SCHEMA_NAME(schema_id) = 'dbo')
   DROP VIEW dbo.Test
GO

IF EXISTS(SELECT * FROM sys.tables WHERE name = 'tblTest' AND SCHEMA_NAME(schema_id) = 'dbo')
   DROP TABLE dbo.tblTest
GO

CREATE TABLE dbo.tblTest
(
   TestId INT NOT NULL IDENTITY(1, 1)
      CONSTRAINT PK_Test PRIMARY KEY CLUSTERED,
   ProblemId INT NOT NULL
      CONSTRAINT FK_Test_ProblemId FOREIGN KEY REFERENCES tblProblem(ProblemId) ON DELETE CASCADE,
   Input NVARCHAR(1000) NOT NULL,
   Output NVARCHAR(1000) NOT NULL,
   CreateDate DATETIME2(2) NOT NULL
      CONSTRAINT DFT_Test_CreateDate DEFAULT SYSUTCDATETIME(),
   UpdateDate DATETIME2(2) NOT NULL
      CONSTRAINT DFT_Test_UpdateDate DEFAULT SYSUTCDATETIME()
)
GO

CREATE VIEW dbo.Test AS SELECT * FROM dbo.tblTest
GO
