SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET QUOTED_IDENTIFIER ON
GO

IF EXISTS(SELECT * FROM sys.views WHERE name = 'LessonVote' AND SCHEMA_NAME(schema_id) = 'dbo')
   DROP VIEW dbo.LessonVote
GO

IF EXISTS(SELECT * FROM sys.tables WHERE name = 'tblLessonVote' AND SCHEMA_NAME(schema_id) = 'dbo')
   DROP TABLE dbo.tblLessonVote
GO

CREATE TABLE dbo.tblLessonVote
(
   LessonVoteId INT NOT NULL IDENTITY(1, 1)
      CONSTRAINT PK_LessonVote PRIMARY KEY CLUSTERED,
   LessonId INT NOT NULL
      CONSTRAINT FK_LessonVote_LessonId FOREIGN KEY REFERENCES tblLesson(LessonId) ON DELETE CASCADE,
   AuthorId UNIQUEIDENTIFIER
      CONSTRAINT FK_LessonVote_AuthorId FOREIGN KEY REFERENCES tblUser(UserId) ON DELETE SET NULL,
   IsUpvote BIT NOT NULL
      CONSTRAINT DFT_LessonVote_IsUpvote DEFAULT 1,
   CreateDate DATETIME2(2) NOT NULL
      CONSTRAINT DFT_LessonVote_CreateDate DEFAULT SYSUTCDATETIME(),
   UpdateDate DATETIME2(2) NOT NULL
      CONSTRAINT DFT_LessonVote_UpdateDate DEFAULT SYSUTCDATETIME()
)
GO

CREATE VIEW dbo.LessonVote AS SELECT * FROM dbo.tblLessonVote
GO
